# This is the individual part of the synchrotron - useful for tests but not much else
# For running the full synchrotron use examples/configs/synchrotron.yaml

- type: tickit_devices.synchrotron.synchrotron_current.SynchrotronCurrent
  name: sync_current
  inputs: {}
  initial_current: 300
