- tickit_devices.synchrotron.synchrotron_current.SynchrotronCurrent:
    name: sync_current
    inputs: {}
    initial_current: 300
- tickit.devices.sink.Sink:
    name: current_sink
    inputs:
      input: sync_current:current