name: Code CI

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"] # can add windows-latest, macos-latest
        python: ["3.7", "3.8", "3.9"]
        pipenv: ["skip-lock"] # --${flag} will be passed to pipenv command

        include:
          # Add an extra Python3.7 runner to publish wheels and use the lockfile
          - os: "ubuntu-latest"
            python: "3.9"
            pipenv: "deploy"
            publish: true

    name: build/${{ matrix.python }}/${{ matrix.os }}/${{ matrix.pipenv }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          # require history to get back to last tag for version number of branches
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Python Dependencies
        run: |
          pip install pipenv build
          pipenv install --dev --${{ matrix.pipenv }} --python $(python -c 'import sys; print(sys.executable)') && pipenv graph
      - name: Create Sdist and Wheel
        if: matrix.publish
        # Set SOURCE_DATE_EPOCH from git commit for reproducible build
        # https://reproducible-builds.org/
        # Set group writable and umask to do the same to match inside DLS
        run: |
          chmod -R g+w .
          umask 0002
          SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct) python -m build --sdist --wheel
      - name: Run Tests
        run: pipenv run tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          name: ${{ matrix.python }}/${{ matrix.os }}/${{ matrix.pipenv }}
          files: cov.xml

      - name: Upload Wheel and Sdist as artifacts
        if: matrix.publish
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/*
